[[pages]]
path = "app.py"
name = "ä¸»é¡µ"
icon = "ğŸ "

[[pages]]
path = "pages/Data_fetch.py"
name = "å…‰è€¦æ•°æ®"
icon = "ğŸ“š"

[[pages]]
path = "pages/Progress.py"
name = "æ¨¡å—è¿›åº¦"
icon = "ğŸ“Š"

[[pages]]
path = "pages/TestAnalysis.py"
name = "æµ‹è¯•æ•°æ®åˆ†æ"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/BFD_Calculator.py"
name = "åç„¦è·è®¡ç®—å™¨"
icon = "ğŸ”§"

[[pages]]
path = "pages/NA_Calculator.py"
name = "NA è®¡ç®—å™¨"
icon = "ğŸ”¬"

[[pages]]
path = "pages/DataAnalysis.py"
name = "æ•°æ®é›†åˆ†æ"
icon = "ğŸ“"
