[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showErrorDetails = true

[theme]
base = "light"
font = "serif"