[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false
baseUrlPath = ""

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = false

[theme]
base = "light"
